default: &default
# Google Cloud SQL Sample Database Configuration
# ----------------------------------------------
#   adapter: mysql2
#   encoding: utf8
#   pool: 5
#   username: your-mysql-user-here
#   password: your-mysql-password-here
#   host: your-mysql-IPv4-address-here
#   database: your-mysql-database-here

# Google Cloud Datastore Sample Database Configuration
# ----------------------------------------------------
#   dataset_id: your-project-id

# PostgreSQL Sample Database Configuration
# ----------------------------------------
#   adapter: postgresql
#   encoding: unicode
#   pool: 5
#   username: your-postgresql-user-here
#   password: your-postgresql-password-here
#   host: your-postgresql-IPv4-address-here
#   database: your-postgresql-database-here

development:
  <<: *default

production:
  <<: *default

# Test configuration
test:
  # Datastore
  dataset_id: gcd-test-dataset-directory
  host: http://localhost:8080/
  # SQL
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3
